namespace:
  name: dev
springprofile: dev
nameOverride: "tsg-backend-dev"
fullnameOverride: "tsg-backend-dev"
service:
  type: ClusterIP
  port: 8080
image:
  tag: "f814b43fb1d653f9604c97fdb711871066a3fb90"
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: tsg-simulator.com
  tls:
    - hosts:
      - tsg-simulator.com
