namespace:
  name: dev
springprofile: dev
nameOverride: "tsg-backend-dev"
fullnameOverride: "tsg-backend-dev"
service:
  type: ClusterIP
  port: 8080
image:
  tag: "f814b43fb1d653f9604c97fdb711871066a3fb90"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    # -- Provide CORS allowed origin.
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.dev.tsg-simulator.com/"
  hosts:
    - host: api.dev.tsg-simulator.com
      paths:
        - path: "/(.*)"
          pathType: Prefix
          backend:
            service: tsg-backend-dev-controller
            port: 8080