apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-name 
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 88081