apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-controller
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: metrics
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}